# Generated by Django 4.1.5 on 2023-05-11 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_filebasedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='news_caster',
            field=models.CharField(default='salom', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
